services:
  tests:
    build: .
    entrypoint: ["pytest", "--cov=app", "--cov-report=term-missing"]

  weather-api:
    build: .
    container_name: infotecs_weather
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - weather-db:/app/db
    depends_on:
      tests:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  weather-db:
