server {
    listen 443 ssl;
    server_name kirtrub.ru;

    ssl_certificate /etc/letsencrypt/live/kirtrub.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kirtrub.ru/privkey.pem;

    location / {
        proxy_pass http://weather-api:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name kirtrub.ru;

    location / {
        return 301 https://$host$request_uri;
    }
}