name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /root/Infotecs_weather
            git pull origin main

            docker compose -f docker-compose.vps.yml build

            docker compose -f docker-compose.vps.yml run --rm weather-api pytest --cov=app --cov-report=term-missing

            docker compose -f docker-compose.vps.yml down
            docker compose -f docker-compose.vps.yml up -d
            docker image prune -f
